In [7]:
# Import all relevant libraries
# This libraries will provides the data structures,
# numerical operational, and visualization tools
#to handle structured or tabular data.

import pandas as pd # provide the data structures i.e. DataFrame
import numpy as np # use for numeric computations
import matplotlib.pyplot as plt # for visualiztion
import seaborn as sns # visualization

In [8]:
def get_data(data_path):
    df = pd.read_excel(data_path)
    return df

def count_missing_values(df):
    return df.isna().sum()

def remove_missing_values(df, columns=None):
    # no columns specify (default)
    if columns == None:
        df.dropna()
        
    # columns should be a list
    return df.dropna(subset=columns, inplace=True)

In [9]:
file_path = r"Provenance Trial 2026 data.xlsx"

df = get_data(file_path)
df.head()

,No.,Day,Months,Year,Monitoring_team,Planting_year,Plot,Provenance,Provenance2,Line_number,Tree_number,Total_height,Merchantable_height,DBH,Number_shoots,Flowering,Remarks,H/D,TH vs MH
0,1,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,1,19.8,9,24.3,NaN,NaN,NaN,0.814815,1.0
1,2,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,2,thinned,thinned,thinned,NaN,NaN,NaN,NaN,NaN
2,3,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,3,dead,dead,dead,NaN,NaN,NaN,NaN,NaN
3,4,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,4,21,11,26.7,NaN,NaN,NaN,0.786517,1.0
4,5,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,5,dead,dead,dead,NaN,NaN,NaN,NaN,NaN

In [10]:
count_missing_values(df)

No.                       0
Day                       1
Months                    1
Year                      0
Monitoring_team           0
Planting_year             0
Plot                      0
Provenance             9863
Provenance2               0
Line_number               0
Tree_number               0
Total_height             76
Merchantable_height      76
DBH                       0
Number_shoots          9863
Flowering              9843
Remarks                8349
H/D                    4992
TH vs MH               4991
dtype: int64

In [11]:
cols = ['Total_height', 'Merchantable_height']
remove_missing_values(df, cols)
df.head()

,No.,Day,Months,Year,Monitoring_team,Planting_year,Plot,Provenance,Provenance2,Line_number,Tree_number,Total_height,Merchantable_height,DBH,Number_shoots,Flowering,Remarks,H/D,TH vs MH
0,1,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,1,19.8,9,24.3,NaN,NaN,NaN,0.814815,1.0
1,2,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,2,thinned,thinned,thinned,NaN,NaN,NaN,NaN,NaN
2,3,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,3,dead,dead,dead,NaN,NaN,NaN,NaN,NaN
3,4,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,4,21,11,26.7,NaN,NaN,NaN,0.786517,1.0
4,5,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,5,dead,dead,dead,NaN,NaN,NaN,NaN,NaN

In [12]:
count_missing_values(df)

No.                       0
Day                       1
Months                    1
Year                      0
Monitoring_team           0
Planting_year             0
Plot                      0
Provenance             9787
Provenance2               0
Line_number               0
Tree_number               0
Total_height              0
Merchantable_height       0
DBH                       0
Number_shoots          9787
Flowering              9767
Remarks                8349
H/D                    4992
TH vs MH               4991
dtype: int64

In [14]:
# Check for any data that need to be removed from height and dbh
height = 'Total_height'
height2 = 'Merchantable_height'
dbh = 'DBH'

df[height].unique()

array([19.8, 'thinned', 'dead', 21, 20, 21.3, 19, 20.4, 20.3, 21.4, 21.8,
       22.3, 23.2, 22.9, 23.4, 22.1, 22.4, 22.8, 24.8, 22.5, 24.3, 21.1,
       24.1, 23.1, 19.7, 21.7, 19.5, 22.2, 24.5, 23.5, 22.7, 24.2, 23.9,
       23, 21.2, 19.2, 16.6, 18.1, 18.2, 17.2, 19.1, 18.8, 20.5, 20.1,
       18.5, 18.6, 18.7, 19.4, 17.5, 15.75, 17.75, 17.25, 19.25, 16, 17,
       15.5, 21.5, 18.25, 20.75, 19.75, 18, 18.75, 20.25, 16.75, 17.3,
       18.4, 16.9, 19.3, 19.6, 15.4, 19.9, 22, 20.8, 17.8, 23.6, 23.3,
       21.9, 23.8, 27, 21.6, 20.9, 20.7, 17.6, 14.25, 13.25, 15, 15.25,
       14.5, 14.75, 10.25, 16.5, 13.6, 16.7, 14.8, 16.4, 17.9, 16.1, 18.9,
       16.8, 16.2, 12.9, 13.5, 15.7, 14, 11.4, 13, 14.4, 11.9, 12.3, 8.1,
       7.3, 12.4, 11.3, 15.1, 15.8, 13.2, 13.9, 3.1, 12.5, 14.9, 13.8,
       14.1, 14.3, 12.8, 10.9, 12.6, 7.1, 10.1, 9.6, 12.1, 13.1, 10.5,
       13.75, 10, 16.25, 10.75, 12.75, 17.72, 12, 12.25, 11.25, 11, 9.25,
       9.5, 11.5, 8.25, 17.1, 16.3, 15.6, 15.2, 17.4, 18.3, 13.7, 13.3,
       14.7, 10.6, 14.6, 8, 9.75, 9, 6, 15.9, 11.8, 29, 14.2, 20.2, 17.7,
       13.4, 20.6, 21.25, 21.75, 23.25, 24.25, 22.75, 15.3, 5.2, 8.75,
       11.75, 12.2, 12.7, 8.8, 5, 3.5, 'Thinned', 3, 7, 6.5, 7.25, 15.55,
       6.25, 5.5, 8.5, 7.75, 11.2], dtype=object)

In [20]:
# remove thinned and dead trees 
thin_dead = ['Thinned', 'thinned', 'dead']
df = df[~df[[height, height2, dbh]].isin(thin_dead).any(axis=1)]

In [21]:
df.head()

,No.,Day,Months,Year,Monitoring_team,Planting_year,Plot,Provenance,Provenance2,Line_number,Tree_number,Total_height,Merchantable_height,DBH,Number_shoots,Flowering,Remarks,H/D,TH vs MH
0,1,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,1,19.8,9,24.3,NaN,NaN,NaN,0.814815,1.0
3,4,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,4,21,11,26.7,NaN,NaN,NaN,0.786517,1.0
6,7,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,7,20,9.3,27.8,NaN,NaN,NaN,0.719424,1.0
8,9,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,2,2,21.3,10.3,22.8,NaN,NaN,NaN,0.934211,1.0
12,13,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,2,6,19,9,25.7,NaN,NaN,NaN,0.739300,1.0

In [28]:
# review the remarks column
df['Remarks'].unique()

<StringArray>
[         nan,     'forked',       'tall',      'short',       'Tall',
 'top broken',    'climber',    'crooked',     'Forked',      'Short']
Length: 10, dtype: str

In [32]:
# remove forked, crooked, and top broken data
unwanted = ['top broken', 'forked', 'Forked', 'crooked']
df = df[~df['Remarks'].isin(unwanted)]

In [34]:
df.head()

,No.,Day,Months,Year,Monitoring_team,Planting_year,Plot,Provenance,Provenance2,Line_number,Tree_number,Total_height,Merchantable_height,DBH,Number_shoots,Flowering,Remarks,H/D,TH vs MH,Age
0,1,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,1,19.8,9,24.3,NaN,NaN,NaN,0.814815,1.0,11
3,4,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,4,21,11,26.7,NaN,NaN,NaN,0.786517,1.0,11
6,7,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,7,20,9.3,27.8,NaN,NaN,NaN,0.719424,1.0,11
8,9,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,2,2,21.3,10.3,22.8,NaN,NaN,NaN,0.934211,1.0,11
12,13,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,2,6,19,9,25.7,NaN,NaN,NaN,0.739300,1.0,11

In [22]:
# Compute Tree ages
df['Age'] = df['Year'] - df['Planting_year']
df.head()

,No.,Day,Months,Year,Monitoring_team,Planting_year,Plot,Provenance,Provenance2,Line_number,Tree_number,Total_height,Merchantable_height,DBH,Number_shoots,Flowering,Remarks,H/D,TH vs MH,Age
0,1,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,1,19.8,9,24.3,NaN,NaN,NaN,0.814815,1.0,11
3,4,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,4,21,11,26.7,NaN,NaN,NaN,0.786517,1.0,11
6,7,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,1,7,20,9.3,27.8,NaN,NaN,NaN,0.719424,1.0,11
8,9,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,2,2,21.3,10.3,22.8,NaN,NaN,NaN,0.934211,1.0,11
12,13,26.0,3.0,2026,"Emmanuel,Rich,Evelyn,Grace",2015,1,NaN,AS1,2,6,19,9,25.7,NaN,NaN,NaN,0.739300,1.0,11

In [35]:
# check for H/D ratio less than 30
df[df['H/D'] < 30].value_counts()

Series([], Name: count, dtype: int64)

In [37]:
# Extract relevant features for analysis
features = ['Plot', 'Provenance2', 'Tree_number', height, height2, dbh, 'Age']
df = df[features]
df.head()

    Plot Provenance2  Tree_number Total_height Merchantable_height   DBH  Age
0      1         AS1            1         19.8                   9  24.3   11
3      1         AS1            4           21                  11  26.7   11
6      1         AS1            7           20                 9.3  27.8   11
8      1         AS1            2         21.3                10.3  22.8   11
12     1         AS1            6           19                   9  25.7   11

In [42]:
# Compute stems per hectare (SPHA)

# stems per plot
spplt = df.groupby(['Provenance2','Plot']).size().reset_index(name='stems_per_plot')

plot_size = (21*21)/10000

0    408.163265
1    362.811791
2    408.163265
3    204.081633
4     226.75737
Name: stems_per_plot, dtype: object